apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring.svc.cluster.local:9090",
                "version": 1
            }
        ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
  namespace: monitoring
data:
  dashboards.yaml: |-
    {
        "apiVersion": 1,
        "providers": [
            {
                "folder": "Default",
                "name": "default",
                "options": {
                    "path": "/grafana-dashboard-definitions/default"
                },
                "orgId": 1,
                "type": "file"
            }
        ]
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-dashboard
  namespace: monitoring
data:
  kubernetes-dashboard.json: |-
    {
      "id": null,
      "title": "Kubernetes Cluster Monitoring",
      "tags": ["kubernetes"],
      "style": "dark",
      "timezone": "browser",
      "panels": [
        {
          "id": 1,
          "title": "Cluster CPU Usage",
          "type": "stat",
          "targets": [
            {
              "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "percent",
              "min": 0,
              "max": 100
            }
          },
          "gridPos": {
            "h": 8,
            "w": 8,
            "x": 0,
            "y": 0
          }
        },
        {
          "id": 2,
          "title": "Cluster Memory Usage",
          "type": "stat",
          "targets": [
            {
              "expr": "100 * (1 - ((node_memory_MemAvailable_bytes or node_memory_MemFree_bytes) / node_memory_MemTotal_bytes))",
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "percent",
              "min": 0,
              "max": 100
            }
          },
          "gridPos": {
            "h": 8,
            "w": 8,
            "x": 8,
            "y": 0
          }
        },
        {
          "id": 3,
          "title": "Running Pods",
          "type": "stat",
          "targets": [
            {
              "expr": "sum(kube_pod_status_phase{phase=\"Running\"})",
              "refId": "A"
            }
          ],
          "fieldConfig": {
            "defaults": {
              "unit": "short"
            }
          },
          "gridPos": {
            "h": 8,
            "w": 8,
            "x": 16,
            "y": 0
          }
        },
        {
          "id": 4,
          "title": "Pod Status Over Time",
          "type": "graph",
          "targets": [
            {
              "expr": "sum by (phase) (kube_pod_status_phase)",
              "refId": "A",
              "legendFormat": "{{phase}}"
            }
          ],
          "legend": {
            "show": true
          },
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 8
          }
        },
        {
          "id": 5,
          "title": "Node Resource Usage",
          "type": "graph",
          "targets": [
            {
              "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
              "refId": "A",
              "legendFormat": "CPU Usage %"
            },
            {
              "expr": "100 * (1 - ((node_memory_MemAvailable_bytes or node_memory_MemFree_bytes) / node_memory_MemTotal_bytes))",
              "refId": "B",
              "legendFormat": "Memory Usage %"
            }
          ],
          "yAxes": [
            {
              "min": 0,
              "max": 100,
              "unit": "percent"
            }
          ],
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 8
          }
        }
      ],
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "refresh": "30s"
    }
